### ISSUE TITLE
Initial database schema

### ISSUE THREAD

**Issue by judofyr** [realistforeningen/rf-members#1]
Here's the schema we've decided on for the first version:

```
Table: members
Columns:
- id (primary_key, autoincrement)
- name (string)
- term (string). Examples: "V15", "H15", "Lifetime"
- price (integer). In "øre".
- created_at (datetime)
```

We've also been thinking about having a `status`-column (or something similar). Instead of deleting memberships (e.g. if someone mistakenly adds a new member) we would set status to `invalid`. We can add that column when we implement the delete feature.

**Comment by velfundert** [comment]
Wouldn't it be easier and more flexible to replace "term" with some sort of expiration date (typically a Unix timestamp)? You could let lifetime members have something like a negative expiration date or something.

Additionally, I think it would be nice to have a field explaining _who_ added the entry for security purposes (i.e. a signature).

**Comment by judofyr** [comment]
Why is it easier with an expiration date? We now need to do time calculation to show what term the membership is valid for. In any reports we're interested in the term the membership is valid for, not the exact date when it expires. Also, if we have an expiration date we need a `begins_at`-date because `created_at` does not imply that it's valid from this date (e.g. you can buy a membership for next term, or we can add historical data).

Yeah, authorization is a tricky thing. Let's tackle it in a separate issue. I'll add one now.

**Comment by judofyr** [comment]
_Update_: I added the `price` column.

**Comment by velfundert** [comment]
Ok, I admit that "easier" probably isn't the right word, but it's certainly more flexible, because it will let you sell memberships with different durations without needing to add any additional data in the database (or having lists or long strings in the `term`-field). But of course, it's not a huge issue.

When would someone buy a membership for the next term before the previous term had ended?

**Comment by velfundert** [comment]
A signature is really more about accountability rather than authorization. You want some kind of way to be able to tell which memberships are valid and which aren't in case someone abuse our system.

**Comment by judofyr** [comment]
You say "flexibilty", I just see that we're ending up generating the `begins_at` and `expires_at` based on "V15" when we insert the data, and then we need to convert the `begins_at` and `expires_at` back to "V15" when we read it out. If we need more complex timespans we can implement it later.

@skjvlnd mentioned that someone had mentioned that buying a membership for the next term could be useful.

"accountability" is a good choice of word, yes. See issue #2.

**Comment by judofyr** [comment]
Considering this is in production I'd say we have an initial schema :smile:
