### ISSUE TITLE
Blacklisted people

### ISSUE THREAD

**Issue by judofyr** [realistforeningen/rf-members#14]
We need store a list of names blacklisted by HS.

We need a new table:

```
blacklist
  name: String
  created_at: Date
```

and it should be included in search.

**Comment by eistaa** [comment]
Should we include an `expiration_date` field? For those cases where the blacklisting is temporary.

**Comment by judofyr** [comment]
I ended up _not_ storing it in the database, but rather in the config file: #15. As for an `expiration_date`, it's probably easier to implement it later if needed.
