### ISSUE TITLE
Suggestion: Have a list of recently added members at the rigth of the search bar/add mebers

### ISSUE THREAD

**Issue by Androish** [realistforeningen/rf-members#16]
When you want to work asap with adding members you might want to be able to write down the member numbers of the last one(s) entered while adding new members.

Right now if you have one entering into the program and one writing down all the info on membership cards. the latest members added disappear as the next member is being put in.

**Comment by judofyr** [comment]
Hm. I'll see if I can make space for it.

**Comment by alfakr0ll** [comment]
Any update about this?

**Comment by judofyr** [comment]
Fixed in 5c51a1d571e5d7ebe528af2bcd0cf5f05950badb
