### ISSUE TITLE
Show success alert after adding of new member

### ISSUE THREAD

**Issue by benedicteb** [realistforeningen/rf-members#8]
For the moment we redirect to the member list for every added member and on the list page you have a text box which you can use to go back to the member addition page.
Better to only display a green "Added member blabla" without the redirect.

**Comment by eigilhs** [comment]
I agree. The workflow should be "Type name" > "Enter" > "Type new name" > … But it is very useful to be able to see the last addition(s) while filling out the membership card(s), even if another volunteer is already entering a new name.

**Comment by benedicteb** [comment]
> But it is very useful to be able to see the last addition(s) while filling out the membership card(s), even if another volunteer is already entering a new name.

Agreed, created #10

**Comment by benedicteb** [comment]
Added in #12
